server.port=8081
spring.application.name=order-service

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://logistics-postgres:5432/order_db
spring.datasource.username=logistics_user
spring.datasource.password=logistics_password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# RabbitMQ Configuration
spring.rabbitmq.host=logistics-rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=adminpassword
